### ISSUE TITLE
[Request] Config option for always day or always night

### ISSUE THREAD

**Issue by lockeslylcrit** [PriestTheBeast/Compressed-Factory#10]
I use this mod for breeding cave dwelling Forestry bees, and since Gendustry allows us to make custom bees I thought Compressed Factory is a perfect place to breed up custom bees that cannot work in the day.

I would love it if the dimension(s) had a config option to set the permanent time of day to either day or night (and normal day/night cycle too). Maybe separate config options for each level of factory.

**Comment by PriestTheBeast** [comment]
Im going to change the place for issues, because i dont see them, only saw yours after 10 days.
Will port your request the internal issue page of the curseforge mod project.
Right now i don't know how that day/night cycle stuff is working in the dimension, but i will check it out when i can.
