### ISSUE TITLE
Game Crash When right clicking teleporter to go into factory

### ISSUE THREAD

**Issue by SirTwsted** [PriestTheBeast/Compressed-Factory#3]
I created a structure that has a 3x3x3 space within inside the structure. ""Not Factory"
When I clicked the controller with a stick, it said Factory was created "All Good So Far"
Here is when things went wrong.........
I right clicked the controller with bare hand to teleport to the new factory.
And I got a crash immediately. - This is the crash report.
.
https://pastebin.com/Xkwgxda0
.

**Comment by PriestTheBeast** [comment]
It is fixed, or at least it should not crash. One can always destroy controller and build factory again, but not with crashed game.

**Comment by PriestTheBeast** [comment]
It is fixed, or at least it should not crash. One can always destroy controller and build factory again, but not with crashed game.
