### ISSUE TITLE
CompFac-1.2.3 Update broke existing Controllers and Factory connections

### ISSUE THREAD

**Issue by Vaygrim** [PriestTheBeast/Compressed-Factory#5]
Updating to **compfact-1.2.3.jar** resulted in all of the Compressed Factory Controller blocks being removed from the world, being replaced by a new 'version' of the block under JEI apparently. Upon placing down a new controller in the hole where the original one was... I was able to create a new factory space. Unfortunately my OLD factory space that was holding my Reactor, generating all the power for my base, had been 'disconnected' and I have no way (that I am aware of) for 'reconnecting' that original factory space to my new controller block.

Your mod changelog listed nothing about changing the controller blocks, nor having to remove the old controller blocks from the game world.... and also did not list any possible risks of factory space loss. So you might want to test your updates a tad more, and do more thorough changelogs?

On a related note, can we get a slash command put in to 'reconnect' old factory spaces to a new controller, please?

**Comment by PriestTheBeast** [comment]
This is a issue that only happens on updating to an older world to 1.2.3 or newer, because the blocks compressor was changed.
New update has such command.
Thx for the help vaygrim.
