### ISSUE TITLE
crash to desktop while breaking energy outlet 

### ISSUE THREAD

**Issue by Dragonracer73** [PriestTheBeast/Compressed-Factory#6]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AstralCore (astralsorcery-1.12.2-1.8.2.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.0.0.2.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 12/6/17 4:51 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at compfac.blocks.tileentities.TileEntityEnergyOutletFactory.func_73660_a(TileEntityEnergyOutletFactory.java:65)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at compfac.blocks.tileentities.TileEntityEnergyOutletFactory.func_73660_a(TileEntityEnergyOutletFactory.java:65)

-- Block entity being ticked --
Details:
	Name: minecraft:compfac.tileentityenergyoutletfactory // compfac.blocks.tileentities.TileEntityEnergyOutletFactory
	Block type: ID #265 (tile.energy_outlet_factory // compfac.blocks.BlockEnergyOutletFactory)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (11,3,2), Chunk: (at 11,0,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #265 (tile.energy_outlet_factory // compfac.blocks.BlockEnergyOutletFactory)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 27 Drop: 27
	Level seed: -75586393434570171
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1063446736 bytes (1014 MB) / 2818048000 bytes (2687 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C6 96 mods loaded, 96 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State          | ID                             | Version                  | Source                                        | Signature                                |
	|:-------------- |:------------------------------ |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAA | minecraft                      | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAA | mcp                            | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJAAAAAAAAA | FML                            | 8.0.99.99                | forge-1.12.2-14.23.1.2555-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | forge                          | 14.23.1.2555             | forge-1.12.2-14.23.1.2555-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | akashictome                    | 1.2-10                   | AkashicTome-1.2-10.jar                        | None                                     |
	| UCHIJAAAAAAAAA | tammodized                     | 0.15.3                   | TamModized-1.12.1-0.15.3.jar                  | None                                     |
	| UCHIJAAAAAAAAA | aov                            | 0.7.5                    | AoV-1.12-0.7.5.jar                            | None                                     |
	| UCHIJAAAAAAAAA | crafttweaker                   | 4.0.10                   | CraftTweaker2-1.12-4.0.10.jar                 | None                                     |
	| UCHIJAAAAAAAAA | mtlib                          | @VERSION@                | MTLib-3.0.1.jar                               | None                                     |
	| UCHIJAAAAAAAAA | modtweaker                     | 4.0.5                    | modtweaker-4.0.5.jar                          | None                                     |
	| UCHIJAAAAAAAAA | jei                            | 4.8.4.130                | jei_1.12.2-4.8.4.130.jar                      | None                                     |
	| UCHIJAAAAAAAAA | appleskin                      | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCHIJAAAAAAAAA | appliedenergistics2            | rv5-stable-3             | appliedenergistics2-rv5-stable-3.jar          | None                                     |
	| UCHIJAAAAAAAAA | astralsorcery                  | 1.8.2                    | astralsorcery-1.12.2-1.8.2.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAAAAAAA | autoreglib                     | 1.3-15                   | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCHIJAAAAAAAAA | badwithernocookiereloaded      | 1.12.2-2.12              | badwithernocookiereloaded-1.12.2-2.12.jar     | None                                     |
	| UCHIJAAAAAAAAA | base                           | 3.4.2                    | base-1.12-3.4.2.jar                           | None                                     |
	| UCHIJAAAAAAAAA | baubles                        | 1.5.1                    | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UCHIJAAAAAAAAA | bonsaitrees                    | 1.0.0                    | bonsaitrees-1.0.0-b36.jar                     | None                                     |
	| UCHIJAAAAAAAAA | bookshelf                      | 2.2.500                  | Bookshelf-1.12.2-2.2.500.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAA | cyclopscore                    | 0.10.23                  | CyclopsCore-1.12.2-0.10.23.jar                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAAAAAAA | capabilityproxy                | 2.0.0                    | CapabilityProxy-1.12.2-2.0.0.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAAAAAAA | ctm                            | MC1.12-0.2.3.9           | CTM-MC1.12-0.2.3.9.jar                        | None                                     |
	| UCHIJAAAAAAAAA | chisel                         | MC1.12-0.0.14.18         | Chisel-MC1.12-0.0.14.18.jar                   | None                                     |
	| UCHIJAAAAAAAAA | chiselsandbits                 | 14.9                     | chiselsandbits-14.9.jar                       | None                                     |
	| UCHIJAAAAAAAAA | codechickenlib                 | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAAAAAAA | redstoneflux                   | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAAAAAAA | cofhcore                       | 4.3.6                    | CoFHCore-1.12-4.3.6.14-universal.jar          | None                                     |
	| UCHIJAAAAAAAAA | cofhworld                      | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UCHIJAAAAAAAAA | morpheus                       | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UCHIJAAAAAAAAA | comforts                       | 1.0.0.2                  | comforts-1.12.2-1.0.0.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAAAAAAA | commoncapabilities             | 1.4.0                    | CommonCapabilities-1.12-1.4.0.jar             | None                                     |
	| UCHIJAAAAAAAAA | compfac                        | 1.1.0                    | compfac-1.2.3.jar                             | None                                     |
	| UCHIJAAAAAAAAA | contenttweaker                 | 1.12-4.2.0               | ContentTweaker-1.12-4.2.0.jar                 | None                                     |
	| UCHIJAAAAAAAAA | corail_pillar_extension_chisel | 4.0.0                    | corail_pillar_extension_chisel-4.0.0-1.12.jar | None                                     |
	| UCHIJAAAAAAAAA | ctgui                          | 1.0.0                    | CraftTweaker2-1.12-4.0.10.jar                 | None                                     |
	| UCHIJAAAAAAAAA | crafttweakerjei                | 2.0.0                    | CraftTweaker2-1.12-4.0.10.jar                 | None                                     |
	| UCHIJAAAAAAAAA | custommainmenu                 | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar             | None                                     |
	| UCHIJAAAAAAAAA | p455w0rdslib                   | 2.0.24                   | p455w0rdslib-1.12-2.0.24.jar                  | None                                     |
	| UCHIJAAAAAAAAA | danknull                       | 1.0.14                   | DankNull-1.12-1.0.14.jar                      | None                                     |
	| UCHIJAAAAAAAAA | darkutils                      | 1.7.181                  | DarkUtils-1.12.2-1.7.181.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAAAAAAA | deathcounter                   | 1.0.0                    | DeathCounter-1.12.1-1.0.0.jar                 | None                                     |
	| UCHIJAAAAAAAAA | durabilityshow                 | 5.0.0                    | Durability Show-1.12-5.0.0.jar                | None                                     |
	| UCHIJAAAAAAAAA | everlastingabilities           | 1.3.6                    | EverlastingAbilities-1.12.2-1.3.6.jar         | None                                     |
	| UCHIJAAAAAAAAA | extracells                     | 2.5.7                    | ExtraCells-1.12.2-2.5.7a41.jar                | None                                     |
	| UCHIJAAAAAAAAA | flatcoloredblocks              | mc1.12-6.6               | flatcoloredblocks-mc1.12-6.6.jar              | None                                     |
	| UCHIJAAAAAAAAA | forgelin                       | 1.5.1                    | Forgelin-1.5.1.jar                            | None                                     |
	| UCHIJAAAAAAAAA | gravestone                     | 1.10.0                   | gravestone-1.10.0.jar                         | None                                     |
	| UCHIJAAAAAAAAA | incontrol                      | 3.6.2                    | incontrol-1.12-3.6.2.jar                      | None                                     |
	| UCHIJAAAAAAAAA | teslacorelib                   | 1.0.11                   | tesla-core-lib-1.12-1.0.11.jar                | None                                     |
	| UCHIJAAAAAAAAA | industrialforegoing            | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.5.10-98.jar      | None                                     |
	| UCHIJAAAAAAAAA | industrialmeat                 | 1.12-1.0.2               | industrialmeat-1.12-1.0.2.jar                 | None                                     |
	| UCHIJAAAAAAAAA | integrateddynamics             | 0.9.6                    | IntegratedDynamics-1.12.2-0.9.6.jar           | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAAAAAAA | integrateddynamicscompat       | 1.0.0                    | IntegratedDynamics-1.12.2-0.9.6.jar           | None                                     |
	| UCHIJAAAAAAAAA | integratedtunnels              | 1.3.5                    | IntegratedTunnels-1.12.2-1.3.5.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAAAAAAA | inventorytweaks                | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAAAAAAA | ironbackpacks                  | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar              | None                                     |
	| UCHIJAAAAAAAAA | ironchest                      | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar               | None                                     |
	| UCHIJAAAAAAAAA | journeymap                     | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAAAAAAA | justenoughbuttons              | 1.12-1.2.1               | justenoughbuttons-1.12-1.2.1.jar              | None                                     |
	| UCHIJAAAAAAAAA | jeresources                    | 0.8.6.28                 | JustEnoughResources-1.12.2-0.8.6.28.jar       | None                                     |
	| UCHIJAAAAAAAAA | lostcities                     | 1.0.2                    | lostcities-1.12-1.0.2.jar                     | None                                     |
	| UCHIJAAAAAAAAA | lostsouls                      | 1.0.0                    | lostsouls-1.12-1.0.0.jar                      | None                                     |
	| UCHIJAAAAAAAAA | meecreeps                      | 0.1.6beta                | meecreeps-1.12-0.1.6beta.jar                  | None                                     |
	| UCHIJAAAAAAAAA | mousetweaks                    | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| UCHIJAAAAAAAAA | netherportalfix                | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar             | None                                     |
	| UCHIJAAAAAAAAA | nice                           | 0.1.0                    | nice-1.12-0.1.0.jar                           | None                                     |
	| UCHIJAAAAAAAAA | notenoughwands                 | 1.5.9                    | notenoughwands-1.12-1.5.9.jar                 | None                                     |
	| UCHIJAAAAAAAAA | thermalfoundation              | 2.3.6                    | ThermalFoundation-1.12-2.3.6.16-universal.jar | None                                     |
	| UCHIJAAAAAAAAA | thermalexpansion               | 5.3.6                    | ThermalExpansion-1.12-5.3.6.20-universal.jar  | None                                     |
	| UCHIJAAAAAAAAA | omlib                          | 3.0.0-131                | omlib-1.12.2-3.0.0-131.jar                    | None                                     |
	| UCHIJAAAAAAAAA | openmodularturrets             | 3.0.0-227                | openmodularturrets-1.12.2-3.0.0-227.jar       | None                                     |
	| UCHIJAAAAAAAAA | clayspawn                      | 1.12a                    | Pam's ClaySpawn 1.12a.jar                     | None                                     |
	| UCHIJAAAAAAAAA | rafradek_tf2_weapons           | 1.1.12                   | rafradek_tf2_weapons-1.12-1.1.12.jar          | None                                     |
	| UCHIJAAAAAAAAA | rangedpumps                    | 0.5                      | rangedpumps-0.5.jar                           | None                                     |
	| UCHIJAAAAAAAAA | reauth                         | 3.5.2                    | ReAuth-3.5.2.jar                              | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UCHIJAAAAAAAAA | redstonearsenal                | 2.3.6                    | RedstoneArsenal-1.12-2.3.6.16-universal.jar   | None                                     |
	| UCHIJAAAAAAAAA | xreliquary                     | 1.12.2-1.3.4.724         | Reliquary-1.12.2-1.3.4.724.jar                | None                                     |
	| UCHIJAAAAAAAAA | resourceloader                 | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAAAAAAA | rftools                        | 7.14                     | rftools-1.12-7.14.jar                         | None                                     |
	| UCHIJAAAAAAAAA | roost                          | 1.1.0                    | roost-1.12-1.1.0.jar                          | None                                     |
	| UCHIJAAAAAAAAA | scrap                          | 1.3.1                    | scrap-1.3.1.jar                               | None                                     |
	| UCHIJAAAAAAAAA | storagenetwork                 | 1.12.1-1.1.1             | SimpleStorageNetwork-1.12.1-1.1.1.jar         | None                                     |
	| UCHIJAAAAAAAAA | stg                            | 1.12-1.2.1               | stg-1.12-1.2.1.jar                            | None                                     |
	| UCHIJAAAAAAAAA | theoneprobe                    | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                   | None                                     |
	| UCHIJAAAAAAAAA | thermalcultivation             | 0.1.1                    | ThermalCultivation-1.12-0.1.1.6-universal.jar | None                                     |
	| UCHIJAAAAAAAAA | thermaldynamics                | 2.3.6                    | ThermalDynamics-1.12-2.3.6.13-universal.jar   | None                                     |
	| UCHIJAAAAAAAAA | tp                             | 1.12                     | tinyprogressions-1.12-3.2.10 - Beta.jar       | None                                     |
	| UCHIJAAAAAAAAA | tinyreactors                   | 1.12                     | tinyreactors-1.12-0.5.3.jar                   | None                                     |
	| UCHIJAAAAAAAAA | topaddons                      | 1.12.2-1.1.3             | topaddons-1.12.2-1.1.3.jar                    | None                                     |
	| UCHIJAAAAAAAAA | tothebatpoles                  | 1.12-1.1.0.0             | tothebatpoles-1.12-1.1.0.0.jar                | None                                     |
	| UCHIJAAAAAAAAA | trashslot                      | 8.4.6                    | TrashSlot_1.12.1-8.4.6.jar                    | None                                     |
	| UCHIJAAAAAAAAA | treechopper                    | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| UCHIJAAAAAAAAA | waystones                      | 4.0.17                   | Waystones_1.12.1-4.0.17.jar                   | None                                     |
	| UCHIJAAAAAAAAA | corail_pillar                  | 4.0.0                    | corail_pillar-4.0.0-1.12.jar                  | None                                     |
	| UCHIJAAAAAAAAA | teslacorelib_registries        | 1.0.11                   | tesla-core-lib-1.12-1.0.11.jar                | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.2.jar)
  
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.0.0.2.jar)
  c4.comforts.asm.SleepTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Dragonracer73'/7803637, l='New World', x=-315.15, y=4.00, z=-1462.97]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.3355
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by PriestTheBeast** [comment]
Should not crash anymore when breaking the block.

**Comment by Dragonracer73** [comment]
thnx for the fix
 

    On Sunday, December 17, 2017 10:21 AM, Miguel Martins <notifications@github.com> wrote:
 

 Should not crash anymore when breaking the block.—

**Comment by PriestTheBeast** [comment]
Update is out very soon.
